/**
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#include <string_view>

#include <array>

#include <cassert>

#if __has_include(<magic_enum/magic_enum.hpp>)
// >=magic_enum-0.9.7
#include <magic_enum/magic_enum.hpp>
#else
// <=magic_enum-0.9.6
#include <magic_enum.hpp>
#endif

#include <ztd/ztd.hxx>

#include "types.hxx"

#include "xset/xset-lookup.hxx"

struct panel_lookup_data
{
    std::array<xset::name, MAX_PANELS> panel{};
    std::array<std::array<xset::name, 4>, MAX_PANELS> panel_mode{};
};

static constexpr ztd::map<xset::panel, panel_lookup_data, 24> xset_panel_lookup{{
    {
        xset::panel::show,
        {
            {
                xset::name::panel1_show,
                xset::name::panel2_show,
                xset::name::panel3_show,
                xset::name::panel4_show,
            },
        },
        // No panel mode for this one.
    },
    {
        xset::panel::show_toolbox,
        {
            {
                xset::name::panel1_show_toolbox,
                xset::name::panel2_show_toolbox,
                xset::name::panel3_show_toolbox,
                xset::name::panel4_show_toolbox,
            },
            {{
                {
                    xset::name::panel1_show_toolbox0,
                    xset::name::panel1_show_toolbox1,
                    xset::name::panel1_show_toolbox2,
                    xset::name::panel1_show_toolbox3,
                },
                {
                    xset::name::panel2_show_toolbox0,
                    xset::name::panel2_show_toolbox1,
                    xset::name::panel2_show_toolbox2,
                    xset::name::panel2_show_toolbox3,
                },
                {
                    xset::name::panel3_show_toolbox0,
                    xset::name::panel3_show_toolbox1,
                    xset::name::panel3_show_toolbox2,
                    xset::name::panel3_show_toolbox3,
                },
                {
                    xset::name::panel4_show_toolbox0,
                    xset::name::panel4_show_toolbox1,
                    xset::name::panel4_show_toolbox2,
                    xset::name::panel4_show_toolbox3,
                },
            }},
        },
    },
    {
        xset::panel::show_devmon,
        {
            {
                xset::name::panel1_show_devmon,
                xset::name::panel2_show_devmon,
                xset::name::panel3_show_devmon,
                xset::name::panel4_show_devmon,
            },
            {{
                {
                    xset::name::panel1_show_devmon0,
                    xset::name::panel1_show_devmon1,
                    xset::name::panel1_show_devmon2,
                    xset::name::panel1_show_devmon3,
                },
                {
                    xset::name::panel2_show_devmon0,
                    xset::name::panel2_show_devmon1,
                    xset::name::panel2_show_devmon2,
                    xset::name::panel2_show_devmon3,
                },
                {
                    xset::name::panel3_show_devmon0,
                    xset::name::panel3_show_devmon1,
                    xset::name::panel3_show_devmon2,
                    xset::name::panel3_show_devmon3,
                },
                {
                    xset::name::panel4_show_devmon0,
                    xset::name::panel4_show_devmon1,
                    xset::name::panel4_show_devmon2,
                    xset::name::panel4_show_devmon3,
                },
            }},
        },
    },
    {
        xset::panel::show_dirtree,
        {
            {
                xset::name::panel1_show_dirtree,
                xset::name::panel2_show_dirtree,
                xset::name::panel3_show_dirtree,
                xset::name::panel4_show_dirtree,
            },
            {{
                {
                    xset::name::panel1_show_dirtree0,
                    xset::name::panel1_show_dirtree1,
                    xset::name::panel1_show_dirtree2,
                    xset::name::panel1_show_dirtree3,
                },
                {
                    xset::name::panel2_show_dirtree0,
                    xset::name::panel2_show_dirtree1,
                    xset::name::panel2_show_dirtree2,
                    xset::name::panel2_show_dirtree3,
                },
                {
                    xset::name::panel3_show_dirtree0,
                    xset::name::panel3_show_dirtree1,
                    xset::name::panel3_show_dirtree2,
                    xset::name::panel3_show_dirtree3,
                },
                {
                    xset::name::panel4_show_dirtree0,
                    xset::name::panel4_show_dirtree1,
                    xset::name::panel4_show_dirtree2,
                    xset::name::panel4_show_dirtree3,
                },
            }},
        },
    },
    {
        xset::panel::slider_positions,
        {
            {
                xset::name::panel1_slider_positions,
                xset::name::panel2_slider_positions,
                xset::name::panel3_slider_positions,
                xset::name::panel4_slider_positions,
            },
            {{
                {
                    xset::name::panel1_slider_positions0,
                    xset::name::panel1_slider_positions1,
                    xset::name::panel1_slider_positions2,
                    xset::name::panel1_slider_positions3,
                },
                {
                    xset::name::panel2_slider_positions0,
                    xset::name::panel2_slider_positions1,
                    xset::name::panel2_slider_positions2,
                    xset::name::panel2_slider_positions3,
                },
                {
                    xset::name::panel3_slider_positions0,
                    xset::name::panel3_slider_positions1,
                    xset::name::panel3_slider_positions2,
                    xset::name::panel3_slider_positions3,
                },
                {
                    xset::name::panel4_slider_positions0,
                    xset::name::panel4_slider_positions1,
                    xset::name::panel4_slider_positions2,
                    xset::name::panel4_slider_positions3,
                },
            }},
        },
    },
    {
        xset::panel::list_detailed,
        {
            {
                xset::name::panel1_list_detailed,
                xset::name::panel2_list_detailed,
                xset::name::panel3_list_detailed,
                xset::name::panel4_list_detailed,
            },
            {{
                {
                    xset::name::panel1_list_detailed0,
                    xset::name::panel1_list_detailed1,
                    xset::name::panel1_list_detailed2,
                    xset::name::panel1_list_detailed3,
                },
                {
                    xset::name::panel2_list_detailed0,
                    xset::name::panel2_list_detailed1,
                    xset::name::panel2_list_detailed2,
                    xset::name::panel2_list_detailed3,
                },
                {
                    xset::name::panel3_list_detailed0,
                    xset::name::panel3_list_detailed1,
                    xset::name::panel3_list_detailed2,
                    xset::name::panel3_list_detailed3,
                },
                {
                    xset::name::panel4_list_detailed0,
                    xset::name::panel4_list_detailed1,
                    xset::name::panel4_list_detailed2,
                    xset::name::panel4_list_detailed3,
                },
            }},
        },
    },
    {
        xset::panel::list_icons,
        {
            {
                xset::name::panel1_list_icons,
                xset::name::panel2_list_icons,
                xset::name::panel3_list_icons,
                xset::name::panel4_list_icons,
            },
            {{
                {
                    xset::name::panel1_list_icons0,
                    xset::name::panel1_list_icons1,
                    xset::name::panel1_list_icons2,
                    xset::name::panel1_list_icons3,
                },
                {
                    xset::name::panel2_list_icons0,
                    xset::name::panel2_list_icons1,
                    xset::name::panel2_list_icons2,
                    xset::name::panel2_list_icons3,
                },
                {
                    xset::name::panel3_list_icons0,
                    xset::name::panel3_list_icons1,
                    xset::name::panel3_list_icons2,
                    xset::name::panel3_list_icons3,
                },
                {
                    xset::name::panel4_list_icons0,
                    xset::name::panel4_list_icons1,
                    xset::name::panel4_list_icons2,
                    xset::name::panel4_list_icons3,
                },
            }},
        },
    },
    {
        xset::panel::list_compact,
        {
            {
                xset::name::panel1_list_compact,
                xset::name::panel2_list_compact,
                xset::name::panel3_list_compact,
                xset::name::panel4_list_compact,
            },
            {{
                {
                    xset::name::panel1_list_compact0,
                    xset::name::panel1_list_compact1,
                    xset::name::panel1_list_compact2,
                    xset::name::panel1_list_compact3,
                },
                {
                    xset::name::panel2_list_compact0,
                    xset::name::panel2_list_compact1,
                    xset::name::panel2_list_compact2,
                    xset::name::panel2_list_compact3,
                },
                {
                    xset::name::panel3_list_compact0,
                    xset::name::panel3_list_compact1,
                    xset::name::panel3_list_compact2,
                    xset::name::panel3_list_compact3,
                },
                {
                    xset::name::panel4_list_compact0,
                    xset::name::panel4_list_compact1,
                    xset::name::panel4_list_compact2,
                    xset::name::panel4_list_compact3,
                },
            }},
        },
    },
    {
        xset::panel::list_large,
        {
            {
                xset::name::panel1_list_large,
                xset::name::panel2_list_large,
                xset::name::panel3_list_large,
                xset::name::panel4_list_large,
            },
            {{
                {
                    xset::name::panel1_list_large0,
                    xset::name::panel1_list_large1,
                    xset::name::panel1_list_large2,
                    xset::name::panel1_list_large3,
                },
                {
                    xset::name::panel2_list_large0,
                    xset::name::panel2_list_large1,
                    xset::name::panel2_list_large2,
                    xset::name::panel2_list_large3,
                },
                {
                    xset::name::panel3_list_large0,
                    xset::name::panel3_list_large1,
                    xset::name::panel3_list_large2,
                    xset::name::panel3_list_large3,
                },
                {
                    xset::name::panel4_list_large0,
                    xset::name::panel4_list_large1,
                    xset::name::panel4_list_large2,
                    xset::name::panel4_list_large3,
                },
            }},
        },
    },
    {
        xset::panel::show_hidden,
        {
            {
                xset::name::panel1_show_hidden,
                xset::name::panel2_show_hidden,
                xset::name::panel3_show_hidden,
                xset::name::panel4_show_hidden,
            },
            {{
                {
                    xset::name::panel1_show_hidden0,
                    xset::name::panel1_show_hidden1,
                    xset::name::panel1_show_hidden2,
                    xset::name::panel1_show_hidden3,
                },
                {
                    xset::name::panel2_show_hidden0,
                    xset::name::panel2_show_hidden1,
                    xset::name::panel2_show_hidden2,
                    xset::name::panel2_show_hidden3,
                },
                {
                    xset::name::panel3_show_hidden0,
                    xset::name::panel3_show_hidden1,
                    xset::name::panel3_show_hidden2,
                    xset::name::panel3_show_hidden3,
                },
                {
                    xset::name::panel4_show_hidden0,
                    xset::name::panel4_show_hidden1,
                    xset::name::panel4_show_hidden2,
                    xset::name::panel4_show_hidden3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_name,
        {
            {
                xset::name::panel1_detcol_name,
                xset::name::panel2_detcol_name,
                xset::name::panel3_detcol_name,
                xset::name::panel4_detcol_name,
            },
            {{
                {
                    xset::name::panel1_detcol_name0,
                    xset::name::panel1_detcol_name1,
                    xset::name::panel1_detcol_name2,
                    xset::name::panel1_detcol_name3,
                },
                {
                    xset::name::panel2_detcol_name0,
                    xset::name::panel2_detcol_name1,
                    xset::name::panel2_detcol_name2,
                    xset::name::panel2_detcol_name3,
                },
                {
                    xset::name::panel3_detcol_name0,
                    xset::name::panel3_detcol_name1,
                    xset::name::panel3_detcol_name2,
                    xset::name::panel3_detcol_name3,
                },
                {
                    xset::name::panel4_detcol_name0,
                    xset::name::panel4_detcol_name1,
                    xset::name::panel4_detcol_name2,
                    xset::name::panel4_detcol_name3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_size,
        {
            {
                xset::name::panel1_detcol_size,
                xset::name::panel2_detcol_size,
                xset::name::panel3_detcol_size,
                xset::name::panel4_detcol_size,
            },
            {{
                {
                    xset::name::panel1_detcol_size0,
                    xset::name::panel1_detcol_size1,
                    xset::name::panel1_detcol_size2,
                    xset::name::panel1_detcol_size3,
                },
                {
                    xset::name::panel2_detcol_size0,
                    xset::name::panel2_detcol_size1,
                    xset::name::panel2_detcol_size2,
                    xset::name::panel2_detcol_size3,
                },
                {
                    xset::name::panel3_detcol_size0,
                    xset::name::panel3_detcol_size1,
                    xset::name::panel3_detcol_size2,
                    xset::name::panel3_detcol_size3,
                },
                {
                    xset::name::panel4_detcol_size0,
                    xset::name::panel4_detcol_size1,
                    xset::name::panel4_detcol_size2,
                    xset::name::panel4_detcol_size3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_bytes,
        {
            {
                xset::name::panel1_detcol_bytes,
                xset::name::panel2_detcol_bytes,
                xset::name::panel3_detcol_bytes,
                xset::name::panel4_detcol_bytes,
            },
            {{
                {
                    xset::name::panel1_detcol_bytes0,
                    xset::name::panel1_detcol_bytes1,
                    xset::name::panel1_detcol_bytes2,
                    xset::name::panel1_detcol_bytes3,
                },
                {
                    xset::name::panel2_detcol_bytes0,
                    xset::name::panel2_detcol_bytes1,
                    xset::name::panel2_detcol_bytes2,
                    xset::name::panel2_detcol_bytes3,
                },
                {
                    xset::name::panel3_detcol_bytes0,
                    xset::name::panel3_detcol_bytes1,
                    xset::name::panel3_detcol_bytes2,
                    xset::name::panel3_detcol_bytes3,
                },
                {
                    xset::name::panel4_detcol_bytes0,
                    xset::name::panel4_detcol_bytes1,
                    xset::name::panel4_detcol_bytes2,
                    xset::name::panel4_detcol_bytes3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_type,
        {
            {
                xset::name::panel1_detcol_type,
                xset::name::panel2_detcol_type,
                xset::name::panel3_detcol_type,
                xset::name::panel4_detcol_type,
            },
            {{
                {
                    xset::name::panel1_detcol_type0,
                    xset::name::panel1_detcol_type1,
                    xset::name::panel1_detcol_type2,
                    xset::name::panel1_detcol_type3,
                },
                {
                    xset::name::panel2_detcol_type0,
                    xset::name::panel2_detcol_type1,
                    xset::name::panel2_detcol_type2,
                    xset::name::panel2_detcol_type3,
                },
                {
                    xset::name::panel3_detcol_type0,
                    xset::name::panel3_detcol_type1,
                    xset::name::panel3_detcol_type2,
                    xset::name::panel3_detcol_type3,
                },
                {
                    xset::name::panel4_detcol_type0,
                    xset::name::panel4_detcol_type1,
                    xset::name::panel4_detcol_type2,
                    xset::name::panel4_detcol_type3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_mime,
        {
            {
                xset::name::panel1_detcol_mime,
                xset::name::panel2_detcol_mime,
                xset::name::panel3_detcol_mime,
                xset::name::panel4_detcol_mime,
            },
            {{
                {
                    xset::name::panel1_detcol_mime0,
                    xset::name::panel1_detcol_mime1,
                    xset::name::panel1_detcol_mime2,
                    xset::name::panel1_detcol_mime3,
                },
                {
                    xset::name::panel2_detcol_mime0,
                    xset::name::panel2_detcol_mime1,
                    xset::name::panel2_detcol_mime2,
                    xset::name::panel2_detcol_mime3,
                },
                {
                    xset::name::panel3_detcol_mime0,
                    xset::name::panel3_detcol_mime1,
                    xset::name::panel3_detcol_mime2,
                    xset::name::panel3_detcol_mime3,
                },
                {
                    xset::name::panel4_detcol_mime0,
                    xset::name::panel4_detcol_mime1,
                    xset::name::panel4_detcol_mime2,
                    xset::name::panel4_detcol_mime3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_perm,
        {
            {
                xset::name::panel1_detcol_perm,
                xset::name::panel2_detcol_perm,
                xset::name::panel3_detcol_perm,
                xset::name::panel4_detcol_perm,
            },
            {{
                {
                    xset::name::panel1_detcol_perm0,
                    xset::name::panel1_detcol_perm1,
                    xset::name::panel1_detcol_perm2,
                    xset::name::panel1_detcol_perm3,
                },
                {
                    xset::name::panel2_detcol_perm0,
                    xset::name::panel2_detcol_perm1,
                    xset::name::panel2_detcol_perm2,
                    xset::name::panel2_detcol_perm3,
                },
                {
                    xset::name::panel3_detcol_perm0,
                    xset::name::panel3_detcol_perm1,
                    xset::name::panel3_detcol_perm2,
                    xset::name::panel3_detcol_perm3,
                },
                {
                    xset::name::panel4_detcol_perm0,
                    xset::name::panel4_detcol_perm1,
                    xset::name::panel4_detcol_perm2,
                    xset::name::panel4_detcol_perm3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_owner,
        {
            {
                xset::name::panel1_detcol_owner,
                xset::name::panel2_detcol_owner,
                xset::name::panel3_detcol_owner,
                xset::name::panel4_detcol_owner,
            },
            {{
                {
                    xset::name::panel1_detcol_owner0,
                    xset::name::panel1_detcol_owner1,
                    xset::name::panel1_detcol_owner2,
                    xset::name::panel1_detcol_owner3,
                },
                {
                    xset::name::panel2_detcol_owner0,
                    xset::name::panel2_detcol_owner1,
                    xset::name::panel2_detcol_owner2,
                    xset::name::panel2_detcol_owner3,
                },
                {
                    xset::name::panel3_detcol_owner0,
                    xset::name::panel3_detcol_owner1,
                    xset::name::panel3_detcol_owner2,
                    xset::name::panel3_detcol_owner3,
                },
                {
                    xset::name::panel4_detcol_owner0,
                    xset::name::panel4_detcol_owner1,
                    xset::name::panel4_detcol_owner2,
                    xset::name::panel4_detcol_owner3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_group,
        {
            {
                xset::name::panel1_detcol_group,
                xset::name::panel2_detcol_group,
                xset::name::panel3_detcol_group,
                xset::name::panel4_detcol_group,
            },
            {{
                {
                    xset::name::panel1_detcol_group0,
                    xset::name::panel1_detcol_group1,
                    xset::name::panel1_detcol_group2,
                    xset::name::panel1_detcol_group3,
                },
                {
                    xset::name::panel2_detcol_group0,
                    xset::name::panel2_detcol_group1,
                    xset::name::panel2_detcol_group2,
                    xset::name::panel2_detcol_group3,
                },
                {
                    xset::name::panel3_detcol_group0,
                    xset::name::panel3_detcol_group1,
                    xset::name::panel3_detcol_group2,
                    xset::name::panel3_detcol_group3,
                },
                {
                    xset::name::panel4_detcol_group0,
                    xset::name::panel4_detcol_group1,
                    xset::name::panel4_detcol_group2,
                    xset::name::panel4_detcol_group3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_atime,
        {
            {
                xset::name::panel1_detcol_atime,
                xset::name::panel2_detcol_atime,
                xset::name::panel3_detcol_atime,
                xset::name::panel4_detcol_atime,
            },
            {{
                {
                    xset::name::panel1_detcol_atime0,
                    xset::name::panel1_detcol_atime1,
                    xset::name::panel1_detcol_atime2,
                    xset::name::panel1_detcol_atime3,
                },
                {
                    xset::name::panel2_detcol_atime0,
                    xset::name::panel2_detcol_atime1,
                    xset::name::panel2_detcol_atime2,
                    xset::name::panel2_detcol_atime3,
                },
                {
                    xset::name::panel3_detcol_atime0,
                    xset::name::panel3_detcol_atime1,
                    xset::name::panel3_detcol_atime2,
                    xset::name::panel3_detcol_atime3,
                },
                {
                    xset::name::panel4_detcol_atime0,
                    xset::name::panel4_detcol_atime1,
                    xset::name::panel4_detcol_atime2,
                    xset::name::panel4_detcol_atime3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_btime,
        {
            {
                xset::name::panel1_detcol_btime,
                xset::name::panel2_detcol_btime,
                xset::name::panel3_detcol_btime,
                xset::name::panel4_detcol_btime,
            },
            {{
                {
                    xset::name::panel1_detcol_btime0,
                    xset::name::panel1_detcol_btime1,
                    xset::name::panel1_detcol_btime2,
                    xset::name::panel1_detcol_btime3,
                },
                {
                    xset::name::panel2_detcol_btime0,
                    xset::name::panel2_detcol_btime1,
                    xset::name::panel2_detcol_btime2,
                    xset::name::panel2_detcol_btime3,
                },
                {
                    xset::name::panel3_detcol_btime0,
                    xset::name::panel3_detcol_btime1,
                    xset::name::panel3_detcol_btime2,
                    xset::name::panel3_detcol_btime3,
                },
                {
                    xset::name::panel4_detcol_btime0,
                    xset::name::panel4_detcol_btime1,
                    xset::name::panel4_detcol_btime2,
                    xset::name::panel4_detcol_btime3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_ctime,
        {
            {
                xset::name::panel1_detcol_ctime,
                xset::name::panel2_detcol_ctime,
                xset::name::panel3_detcol_ctime,
                xset::name::panel4_detcol_ctime,
            },
            {{
                {
                    xset::name::panel1_detcol_ctime0,
                    xset::name::panel1_detcol_ctime1,
                    xset::name::panel1_detcol_ctime2,
                    xset::name::panel1_detcol_ctime3,
                },
                {
                    xset::name::panel2_detcol_ctime0,
                    xset::name::panel2_detcol_ctime1,
                    xset::name::panel2_detcol_ctime2,
                    xset::name::panel2_detcol_ctime3,
                },
                {
                    xset::name::panel3_detcol_ctime0,
                    xset::name::panel3_detcol_ctime1,
                    xset::name::panel3_detcol_ctime2,
                    xset::name::panel3_detcol_ctime3,
                },
                {
                    xset::name::panel4_detcol_ctime0,
                    xset::name::panel4_detcol_ctime1,
                    xset::name::panel4_detcol_ctime2,
                    xset::name::panel4_detcol_ctime3,
                },
            }},
        },
    },
    {
        xset::panel::detcol_mtime,
        {
            {
                xset::name::panel1_detcol_mtime,
                xset::name::panel2_detcol_mtime,
                xset::name::panel3_detcol_mtime,
                xset::name::panel4_detcol_mtime,
            },
            {{
                {
                    xset::name::panel1_detcol_mtime0,
                    xset::name::panel1_detcol_mtime1,
                    xset::name::panel1_detcol_mtime2,
                    xset::name::panel1_detcol_mtime3,
                },
                {
                    xset::name::panel2_detcol_mtime0,
                    xset::name::panel2_detcol_mtime1,
                    xset::name::panel2_detcol_mtime2,
                    xset::name::panel2_detcol_mtime3,
                },
                {
                    xset::name::panel3_detcol_mtime0,
                    xset::name::panel3_detcol_mtime1,
                    xset::name::panel3_detcol_mtime2,
                    xset::name::panel3_detcol_mtime3,
                },
                {
                    xset::name::panel4_detcol_mtime0,
                    xset::name::panel4_detcol_mtime1,
                    xset::name::panel4_detcol_mtime2,
                    xset::name::panel4_detcol_mtime3,
                },
            }},
        },
    },
    {
        xset::panel::sort_extra,
        {
            {
                xset::name::panel1_sort_extra,
                xset::name::panel2_sort_extra,
                xset::name::panel3_sort_extra,
                xset::name::panel4_sort_extra,
            },
            {{
                {
                    xset::name::panel1_sort_extra0,
                    xset::name::panel1_sort_extra1,
                    xset::name::panel1_sort_extra2,
                    xset::name::panel1_sort_extra3,
                },
                {
                    xset::name::panel2_sort_extra0,
                    xset::name::panel2_sort_extra1,
                    xset::name::panel2_sort_extra2,
                    xset::name::panel2_sort_extra3,
                },
                {
                    xset::name::panel3_sort_extra0,
                    xset::name::panel3_sort_extra1,
                    xset::name::panel3_sort_extra2,
                    xset::name::panel3_sort_extra3,
                },
                {
                    xset::name::panel4_sort_extra0,
                    xset::name::panel4_sort_extra1,
                    xset::name::panel4_sort_extra2,
                    xset::name::panel4_sort_extra3,
                },
            }},
        },
    },
    {
        xset::panel::book_fol,
        {
            {
                xset::name::panel1_book_fol,
                xset::name::panel2_book_fol,
                xset::name::panel3_book_fol,
                xset::name::panel4_book_fol,
            },
            {{
                {
                    xset::name::panel1_book_fol0,
                    xset::name::panel1_book_fol1,
                    xset::name::panel1_book_fol2,
                    xset::name::panel1_book_fol3,
                },
                {
                    xset::name::panel2_book_fol0,
                    xset::name::panel2_book_fol1,
                    xset::name::panel2_book_fol2,
                    xset::name::panel2_book_fol3,
                },
                {
                    xset::name::panel3_book_fol0,
                    xset::name::panel3_book_fol1,
                    xset::name::panel3_book_fol2,
                    xset::name::panel3_book_fol3,
                },
                {
                    xset::name::panel4_book_fol0,
                    xset::name::panel4_book_fol1,
                    xset::name::panel4_book_fol2,
                    xset::name::panel4_book_fol3,
                },
            }},
        },
    },
}};

// panel

xset::name
xset::get_name_from_panel(const panel_t panel, const xset::panel name) noexcept
{
    assert(panel == panel_1 || panel == panel_2 || panel == panel_3 || panel == panel_4);

    return xset_panel_lookup.at(name).panel[panel - 1];
}

// panel mode

xset::name
xset::get_name_from_panel_mode(const panel_t panel, const xset::panel name,
                               const xset::main_window_panel mode) noexcept
{
    assert(panel == panel_1 || panel == panel_2 || panel == panel_3 || panel == panel_4);
    assert(name != xset::panel::show);

    return xset_panel_lookup.at(name).panel_mode[panel - 1][magic_enum::enum_integer(mode)];
}

// main window panel mode

std::string_view
xset::get_window_panel_mode(xset::main_window_panel mode) noexcept
{
    static constexpr ztd::map<xset::main_window_panel, std::string_view, 4>
        main_window_panel_mode_map{{
            {xset::main_window_panel::panel_neither, "0"},
            {xset::main_window_panel::panel_horiz, "1"},
            {xset::main_window_panel::panel_vert, "2"},
            {xset::main_window_panel::panel_both, "3"},
        }};

    return main_window_panel_mode_map.at(mode);
}
